### ISSUE TITLE
[Bug]: Crash with Fabric API 0.60.0+1.19.2

### ISSUE THREAD

**Issue by endavis** [ThatGravyBoat/Duckling#20]
### Bug Description

Crash on startup with Fabric API 0.60.0+1.19.2. It worked with Fabric API 0.59.0+1.19.2.

Full log: https://paste.ee/p/MylDb

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'duckling'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
	at tech.thatgravyboat.duckling.common.registry.fabric.ModSpawnsImpl.setSpawnRules(ModSpawnsImpl.java:11)
	at tech.thatgravyboat.duckling.common.registry.ModSpawns.setSpawnRules(ModSpawns.java)
	at tech.thatgravyboat.duckling.common.registry.ModSpawns.addSpawnRules(ModSpawns.java:13)
	at tech.thatgravyboat.duckling.fabric.DucklingFabric.onInitialize(DucklingFabric.java:23)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

### How to Reproduce?

Use Fabric API 0.60.0+1.19.2

### Version

2.0.5

### Mod Loader Version

0.14.9

### Mod Loader

Fabric

### Logs or additional context

https://paste.ee/p/MylDb

**Comment by ThatGravyBoat** [comment]
Fixed in 2.0.6
